export const HYPERSCALER_CAPEX_2026 = [
  { name: "Amazon / AWS", capex: 200, color: "#FF9900" },
  { name: "Alphabet / Google", capex: 180, color: "#4285F4" },
  { name: "Meta", capex: 125, color: "#1877F2" },
  { name: "Microsoft", capex: 120, color: "#00A4EF" },
  { name: "Oracle", capex: 50, color: "#F80000" },
];

export const TOP_PROJECTS = [
  { company: "Anthropic / Fluidstack", project: "US AI Infrastructure Program", location: "NY/TX Initial", state: "Multi", status: "Announced", capex: "$50B", constructionJobs: "2,000+", permJobs: "800+" },
  { company: "Stargate (OpenAI/Oracle/SoftBank)", project: "Stargate Program Total", location: "National", state: "Multi", status: "Mixed", capex: "$500B", constructionJobs: "30,000+", permJobs: "TBD" },
  { company: "Google", project: "Texas Program", location: "Multiple TX Counties", state: "TX", status: "Planned", capex: "$40B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "AWS", project: "Mississippi Program", location: "Canton/Clinton/Vicksburg", state: "MS", status: "Construction", capex: "$25B", constructionJobs: "Thousands", permJobs: "2,000" },
  { company: "Vantage", project: "Frontier Campus", location: "Texas", state: "TX", status: "Planned", capex: "$25B", constructionJobs: "5,000+", permJobs: "TBD" },
  { company: "Meta", project: "Hyperion", location: "Rayville/Delhi Area", state: "LA", status: "Construction", capex: "$27B", constructionJobs: "5,000", permJobs: "500" },
  { company: "AWS", project: "Pennsylvania Program", location: "Multiple PA", state: "PA", status: "Planned", capex: "$20B", constructionJobs: "Thousands", permJobs: "1,250" },
  { company: "xAI", project: "MACROHARDRR Southaven", location: "Southaven", state: "MS", status: "Construction", capex: "$20B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "Joliet / PowerHouse", project: "Joliet Technology Center", location: "Joliet", state: "IL", status: "Approved", capex: "$20B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "Vantage", project: "Lighthouse Campus", location: "Port Washington", state: "WI", status: "Construction", capex: "$15B", constructionJobs: "4,000+", permJobs: "1,000+" },
  { company: "AWS", project: "Indiana Program", location: "St. Joseph County", state: "IN", status: "Construction", capex: "$11B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "OpenAI / Oracle / Crusoe", project: "Stargate Abilene", location: "Abilene", state: "TX", status: "Construction", capex: "$11.6B+", constructionJobs: "5,000+", permJobs: "357" },
  { company: "AWS", project: "Georgia Program", location: "Multiple GA", state: "GA", status: "Planned", capex: "$11B", constructionJobs: "Thousands", permJobs: "Hundreds" },
  { company: "AWS", project: "North Carolina Program", location: "Hamlet/Rockingham", state: "NC", status: "Construction", capex: "$10B", constructionJobs: "Thousands", permJobs: "500" },
  { company: "Meta", project: "El Paso Campus", location: "El Paso", state: "TX", status: "Construction", capex: "$10B+", constructionJobs: "4,000+", permJobs: "300+" },
  { company: "AWS", project: "Ohio Program", location: "Multiple OH", state: "OH", status: "Construction", capex: "$10B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "AWS", project: "KC Northland Campus", location: "Kansas City", state: "MO", status: "Planned", capex: "$10B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "Microsoft", project: "Fairwater AI Superfactory", location: "Atlanta", state: "GA", status: "Construction", capex: "$80B", constructionJobs: "1,324", permJobs: "635+" },
  { company: "AVAIO Digital", project: "Leo Campus", location: "Little Rock", state: "AR", status: "Construction", capex: "$6B+", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "ESS", project: "Tarboro Campus", location: "Tarboro", state: "NC", status: "Planned", capex: "$6.4B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "CoreWeave", project: "Lancaster Campus", location: "Lancaster", state: "PA", status: "Construction", capex: "$6B", constructionJobs: "600+", permJobs: "175+" },
  { company: "Aligned", project: "Project Caprock", location: "Hale County", state: "TX", status: "Planned", capex: "$5B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "Cologix", project: "Johnstown Campus", location: "Johnstown", state: "OH", status: "Construction", capex: "$7B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "Microsoft", project: "Mount Pleasant Campus", location: "Mount Pleasant", state: "WI", status: "Construction", capex: "$7B", constructionJobs: "2,000+", permJobs: "800+" },
  { company: "Microsoft", project: "Project Steamboat", location: "Fulton County", state: "GA", status: "Approved", capex: "$1.8B", constructionJobs: "TBD", permJobs: "TBD" },
  { company: "QTS", project: "Dane County Mega Campus", location: "DeForest", state: "WI", status: "Planned", capex: "$12B", constructionJobs: "5,000+", permJobs: "TBD" },
  { company: "NTT", project: "US Expansion Program", location: "Chicago/Dallas/Phoenix", state: "Multi", status: "Mixed", capex: "$10B", constructionJobs: "TBD", permJobs: "TBD" },
];

export const STATES_DATA = [
  { state: "VA", state_name: "Virginia", operational: 300, pipeline: 60, commissionedMW: 4000, gdpB: 9.1, localTaxB: 1.64, jobs: 74000, multiplier: 3.5, notes: "Loudoun 26:1 fiscal ratio. 84% of all VA capex in 2024." },
  { state: "TX", state_name: "Texas", operational: 400, pipeline: 90, commissionedMW: 4000, ucMW: 8000, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Projected #1 market by 2030. Stargate flagship." },
  { state: "AZ", state_name: "Arizona", operational: 110, pipeline: 40, commissionedMW: 1380, gdpB: 25, localTaxB: 0.863, jobs: null, multiplier: null, notes: "Phoenix #4 N. America. HB2822: 2.5% acquisition cost property tax." },
  { state: "GA", state_name: "Georgia", operational: 80, pipeline: 35, commissionedMW: 1065, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Atlanta #4 US market. Industrial electricity 40% below national avg." },
  { state: "OH", state_name: "Ohio", operational: 100, pipeline: 77, commissionedMW: null, gdpB: null, localTaxB: null, jobs: 4500, multiplier: null, notes: "Columbus becoming #2 Great Lakes hub. DC share: 5.3% → 10.9% energy." },
  { state: "IL", state_name: "Illinois", operational: 120, pipeline: 25, commissionedMW: 805, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Joliet Tech Center $20B. Mandates carbon-neutral within 2 yrs." },
  { state: "CA", state_name: "California", operational: 280, pipeline: 30, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Silicon Valley primary cluster. Supply-constrained market." },
  { state: "FL", state_name: "Florida", operational: 125, pipeline: 30, commissionedMW: 1900, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Emerging market. Subsea cable landings + population growth." },
  { state: "WI", state_name: "Wisconsin", operational: 20, pipeline: 15, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Microsoft Mt Pleasant (800 perm jobs). Vantage Lighthouse $15B." },
  { state: "NC", state_name: "North Carolina", operational: 40, pipeline: 25, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Duke Energy: DC demand 3GW → 6GW in a decade. AWS $10B." },
  { state: "PA", state_name: "Pennsylvania", operational: 30, pipeline: 20, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "AWS $20B = largest private investment in PA history." },
  { state: "MS", state_name: "Mississippi", operational: 5, pipeline: 15, commissionedMW: null, gdpB: null, localTaxB: null, jobs: 2000, multiplier: null, notes: "AWS $25B + xAI $20B. Special legislation: AWS covers power infra costs." },
  { state: "IN", state_name: "Indiana", operational: 15, pipeline: 10, commissionedMW: null, gdpB: null, localTaxB: null, jobs: 1000, multiplier: null, notes: "AWS $11B = largest capex in IN history." },
  { state: "LA", state_name: "Louisiana", operational: 10, pipeline: 10, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Meta Hyperion $27B in Richland Parish." },
  { state: "MO", state_name: "Missouri", operational: 20, pipeline: 15, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "Google KC 500MW; AWS Northland $10B (5 DCs)." },
  { state: "IA", state_name: "Iowa", operational: 25, pipeline: 5, commissionedMW: null, gdpB: null, localTaxB: null, jobs: null, multiplier: null, notes: "$15B invested since mid-2000s. Established cluster." },
];

export const FISCAL_BENEFIT_RATIOS = [
  { name: "Loudoun Co., VA\n(Data Center Alley)", ratio: 26, type: "Data Center", color: "#2563EB" },
  { name: "Prince William Co., VA", ratio: 13, type: "Data Center", color: "#3B82F6" },
  { name: "Mesa, AZ", ratio: 11, type: "Data Center", color: "#60A5FA" },
  { name: "Hillsborough, FL", ratio: 10, type: "Data Center", color: "#93C5FD" },
  { name: "Manufacturing\n(Best Case)", ratio: 4, type: "Manufacturing", color: "#10B981" },
  { name: "Residential", ratio: 0.8, type: "Residential", color: "#F59E0B" },
];

export const ELECTRICITY_PRICE_DATA = [
  { year: "2019", cents: 13 },
  { year: "2020", cents: 13.2 },
  { year: "2021", cents: 14 },
  { year: "2022", cents: 15.4 },
  { year: "2023", cents: 17 },
  { year: "2024", cents: 18 },
  { year: "2025", cents: 19 },
  { year: "2030E", cents: 26.6 },
];

export const DC_ELECTRICITY_SHARE = [
  { year: "2023", share: 4.4 },
  { year: "2026E", share: 6.5 },
  { year: "2028E", share: 9.0 },
  { year: "2030E", share: 10.0 },
];

export const HOST_COUNTIES = [
  {
    county: "Richland Parish, LA",
    anchor: "Meta Hyperion",
    investment: "$27B",
    perCapitaIncome: "$42,298",
    povertyRate: "24%",
    childPoverty: "37%",
    popChange: "-6%",
    verdict: "Transformative",
    color: "#22C55E",
  },
  {
    county: "Taylor County, TX",
    anchor: "Stargate Abilene",
    investment: "$3.5B",
    perCapitaIncome: "Mid-range",
    povertyRate: "~15%",
    childPoverty: "N/A",
    popChange: "Stagnant",
    verdict: "Positive",
    color: "#3B82F6",
  },
  {
    county: "Fulton County, GA",
    anchor: "Project Steamboat",
    investment: "$1.84B",
    perCapitaIncome: "Above avg",
    povertyRate: "~13%",
    childPoverty: "N/A",
    popChange: "+Growth",
    verdict: "Positive",
    color: "#3B82F6",
  },
  {
    county: "Warren County, MS",
    anchor: "AWS Mississippi",
    investment: "$25B+",
    perCapitaIncome: "Below avg",
    povertyRate: "~22%",
    childPoverty: "N/A",
    popChange: "Declining",
    verdict: "Transformative",
    color: "#22C55E",
  },
  {
    county: "St. Joseph County, IN",
    anchor: "AWS Indiana",
    investment: "$11B",
    perCapitaIncome: "Mid-range",
    povertyRate: "~16%",
    childPoverty: "N/A",
    popChange: "Stable",
    verdict: "Positive",
    color: "#3B82F6",
  },
  {
    county: "Newton County, GA",
    anchor: "Meta Mansfield",
    investment: "Operational",
    perCapitaIncome: "Below avg",
    povertyRate: "~18%",
    childPoverty: "N/A",
    popChange: "Growth",
    verdict: "Mixed",
    color: "#F59E0B",
  },
  {
    county: "Pulaski County, AR",
    anchor: "AVAIO Leo Campus",
    investment: "$6B+",
    perCapitaIncome: "Mid-range",
    povertyRate: "~17%",
    childPoverty: "N/A",
    popChange: "Stable",
    verdict: "Positive",
    color: "#3B82F6",
  },
  {
    county: "Taylor County, WI",
    anchor: "Vantage Lighthouse",
    investment: "$15B",
    perCapitaIncome: "Mid-range",
    povertyRate: "~10%",
    childPoverty: "N/A",
    popChange: "Stable",
    verdict: "Positive",
    color: "#3B82F6",
  },
];

export const RATEPAYER_STATE_YOY = [
  { state: "IL", pct: 16 },
  { state: "VA", pct: 13 },
  { state: "OH", pct: 12 },
  { state: "US Avg", pct: 6 },
];

export const PJM_CAPACITY_AUCTION = [
  { period: "2024–25", valueB: 2.2 },
  { period: "2025–26", valueB: 14.7 },
];

export const BROOKINGS_DATA = [
  { metric: "Private Employment Growth", value: "+4–5%" },
  { metric: "Construction Employment", value: "+11%" },
  { metric: "Information Sector Growth", value: "+22%" },
  { metric: "Wage Growth", value: "+3–4%" },
  { metric: "Home Price Impact", value: "Neutral (0%)" },
];

export const PIPELINE_SUMMARY = {
  totalCapexIdentified: 290,
  hyperscalerCapex2026: 675,
  stargateTotal: 500,
  operationalFacilities: 4000,
  plannedFacilities: 3000,
  constructionJobs: 40000,
  permanentJobs: 10000,
  usElectricShareNow: 4.4,
  usElectricShare2030: 8,
  usElectricLoadGrowthShare: 60,
  ytdApril2026Capex: 49.5,
  ytdApril2026Projects: 74,
  nearTermPipelineCapex: 92.1,
  nearTermPipelineProjects: 65,
  ratepayerBurden7States: 4.3,
  waterDailyGallions449M: 449,
  pjmAuctionJump: 568,
};
